# Generated by Django 4.2 on 2023-12-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_news_html_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
    ]
