# Generated by Django 4.2 on 2023-12-18 22:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_remove_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='html_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
